// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Please ensure these are set in your environment.`;
    console.error(`[Supabase Client] ${message}`);
    
    // In SPA on Vercel, if Supabase isn't configured, throw error with clear context
    // This prevents hydration mismatches and allows React to properly handle the error
    const error = new Error(message);
    error.name = 'SupabaseConfigurationError';
    throw error;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _initError: Error | null = null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    // If initialization failed before, throw the same error again
    if (_initError) {
      throw _initError;
    }
    
    try {
      if (!_supabase) {
        _supabase = createSupabaseClient();
      }
      return Reflect.get(_supabase, prop, receiver);
    } catch (error) {
      // Cache the error so subsequent accesses throw the same error
      _initError = error instanceof Error ? error : new Error(String(error));
      throw _initError;
    }
  },
});

